### PR TITLE
Can build a single specified language

### PR DESCRIPTION
**Pull request by olets**
Inspired by https://www.viget.com/articles/unscramble-a-programming-challenge/ 's call for reader contributions:

Adds support for testing one specific language. Means a contributor can test their implementation without altering the Rakefile or setting up all the languages. Chose Bash for the README example as a language pretty much anyone will be able to try the command with.

Also adds a .tool-versions with Ruby 2.3.8. The exact version is somewhat arbitrary, but it works (unlike my shell's current default 2.1.0). Happy to update to something more exactly necessary

### CODE REVIEW

**Comment by olets** [comment]
p.s. More contributor DX: just tested my Zsh solution on Linux and found there isn't necessarily a `/usr/share/dict/words`. Won't add a commit to this branch yet because I'm not sure if it's within the project's scope to help debug setup, but could add something like this to the readme

> Note that the tests run against English words. If you use a different language, symlink `/usr/share/dict/words` to an English word list to run the tests. If you do not have an English word list installed, install `wamerican` or `wbritish` (e.g. `apt-get install wamerican`); [english-words](https://github.com/dwyl/english-words)'s `words.txt` will do as well.

**Comment by cwmanning** [comment]
@olets so you can't do something like run `tail /usr/share/dict/words` and see some of the list? what version of OS X? https://en.wikipedia.org/wiki/Words_(Unix) is the intended resource

**Comment by cwmanning** [comment]
oh, on Linux! my mistake. would you mind adding a note? everything else looks good to me!

**Comment by olets** [comment]
@cwmanning done! 852546c

**Review by cwmanning — APPROVED** [review]

**Pull request merged**
