### PR TITLE
Add Swift solution

### PR DESCRIPTION
**Pull request by prayash**
Went with lexicographical sorting, the permutations approach was way too slow.

### CODE REVIEW

**Comment by prayash** [comment]
@cwmanning Mind taking a look and seeing if you can run this with the entire suite? Not sure if I set everything up correctly here

**Comment by cwmanning** [comment]
No problem. It works for me

```
  * Entering directory 'languages/Swift'
    * Running task 'Swift:clean'... not found.
    * Running task 'Swift:build'... done.
    * Running tests...Run options: --seed 14085

# Running:

.........

Finished in 6.134462s, 1.4671 runs/s, 1.4671 assertions/s.
9 runs, 9 assertions, 0 failures, 0 errors, 0 skips
done.
```

**Review by cwmanning — APPROVED** [review]
👍

**Comment by prayash** [comment]
Sweet! Gonna go ahead and merge er in

**Pull request merged**
